config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :products
  resources :sub_categories
  resources :reviews
  resources :cart_line_items

  root 'products#index'

end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base

  belongs_to :product
  belongs_to :user
  validates_presence_of :product_id, :user_id, :quantity
  validates_numericality_of :product_id, :user_id, greater_than: 0
  validates_numericality_of :quantity, within: 1..5

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  has_many :sub_categories
  #validations
  validates_presence_of :name
  validates_uniqueness_of :name

  def formatted_name
    "#{self.id} - #{self.name}"
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :cart_line_items
  belongs_to :category
  belongs_to :sub_category

  # inbuilt validations
  validates_presence_of :name, :price, :category_id, :description, :stock, :sub_category_id
  validates_numericality_of :price, greater_than: 1
  validates_numericality_of :sub_category_id
  validates_numericality_of :stock, greater_than_or_equal_to: 0
  validates_numericality_of :category_id, greater_than: 0
  validates_length_of :description, minimum: 10
  validates_length_of :name, minimum: 4
  validate :check_for_based_on_price
  validate :check_for_category
  #custom validations
  def check_for_based_on_price
    if !self.price.nil?
      if self.price > 50000 && self.cod_eligibility
        self.errors.add(:cod_eligibility, "not available for products greater than 50000")
      end
    end
  end
  def check_for_category
    if !self.category_id.nil?
      if (self.category_id == 1 || self.category_id == 2) && self.cod_eligibility
        self.errors.add(:cod_eligibility, "not available for this products")
      end
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  validates_presence_of :product_id, :user_id, :title, :rating
  validates_numericality_of :product_id, :user_id, greater_than: 0
  validates_numericality_of :rating, within: 1..5 # inclusive range if ... exclusive range
  validates_length_of :body, minimum: 10, allow_blank: true
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  has_many :products
  belongs_to :category
  validates_presence_of :name, :category_id
  validates_uniqueness_of :name
  validates_numericality_of :category_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  has_many :cart_line_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_line_items_controller.rb
class CartLineItemsController < ApplicationController

  def index
    @cart_line_items = current_user.cart_line_items
  end
  def create
    @cart_line_item = CartLineItem.new(cart_line_item_params)
    @cart_line_item.user_id = current_user.id
    if @cart_line_item.save
      redirect_to cart_line_items_path, notice: "you have added the product to the cart"
    end
  end
  private
  def cart_line_item_params
    params[:cart_line_item].permit(:product_id, :quantity)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
=begin
  
index
new
create
show
edit 
update
destroy
=end
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category].permit(:name))
    if @category.save
      redirect_to "/categories", notice: "Sucessfully created #{@category.name}" #categories_path
    else
      render action: "new"
    end
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
    # @products = Product.where('category_id=?',@category.id)
    @products_lessthan500 = Product.where('category_id=? AND price<?',@category.id,500)
    @products_greaterthan500 = Product.where('category_id=? AND price>?',@category.id,500)
  end
  def edit
    @category = Category.find(params[:id])
  end
  def update
    @category = Category.find(params[:id])
    previous_name = @category.name
    if @category.update_attributes(params[:category].permit(:name))
      redirect_to category_path(@category.id), notice: "Sucessfully updated from #{previous_name} to #{@category.name}"  #redirect_to categories_path
    else render action: "edit"
    end
  end
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice: "Sucessfully deleted #{@category.name}"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def new
    @product = Product.new
  end
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product.id), notice:"sucessfully created a product #{@product.name}"
    else
      render action: "new"
    end
  end
  def show
    begin
      @product = Product.find(params[:id])
      @review = Review.new
      @cart_line_item = CartLineItem.new
    rescue ActiveRecord::RecordNotFound
      redirect_to products_path, notice:"Record Not Found"
    end
  end
  def edit
    @product = Product.find(params[:id])
  end
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to products_path, notice:"sucessfully updated the product #{@product.name}"
    else
      render action: "edit"
    end
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice:"sucessfully deleted the product #{@product.name}"
  end
  private
  def product_params
    params[:product].permit(:name, :description,:price, :stock, :category_id,:cod_eligibility)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to :back, notice: "Thank you for the Review"
    end
  end
  private
  def review_params
    params[:review].permit(:title,:body, :rating, :product_id)
  end
  def show
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
      redirect_to product_path(@review.product_id)
    end
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  def index
    @subcategories = SubCategory.all
  end

  def new
    @subcategory = SubCategory.new
  end

  def create
    @subcategory= SubCategory.new(params[:sub_category].permit(:name,:category_id))
    if @subcategory.save
      redirect_to sub_categories_path,notice:"Succesfully Created Record"
    else
      render new_sub_category_path
    end
  end

  def show
    @subcategory = SubCategory.find(params[:id])
  end

  def edit
    @subcategory = SubCategory.find(params[:id])
  end

  def update
    @subcategory = SubCategory.find(params[:id])
    if @subcategory.update_attributes(params[:sub_category].permit(:name,:category_id))
      redirect_to sub_category_path(@subcategory.id),notice: "Succesfully Updated Record"
    else
      render edit_sub_category_path(@subcategory.id)
    end
  end

  def destroy
    @subcategory = SubCategory.find(params[:id])
    @subcategory.destroy
    redirect_to sub_categories_path,notice:"Succesfully deleted record"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_line_items_helper.rb
module CartLineItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/cart_line_items/index.html.erb
<% if @cart_line_items.empty? %>
<p>your cart is empty? <%= link_to "here", products_path %></p>
<% else %>
<table border="1">
<thead>
<tr>
<th> # </th>
<th> Product </th>
<th> Price </th>
<th> Quantity </th>
<th> Total </th>
</tr>
</thead>
<tbody>
<% @cart_line_items.each_with_index do |cart_line_item, index| %>
<tr>
<td><%= index +1 %></td>
<td><%= cart_line_item.product.name %></td>
<td><%= cart_line_item.product.price %></td>
<td><%= cart_line_item.quantity %></td>
<td><%= cart_line_item.product.price * cart_line_item.quantity %></td>
</tr>
<% end %>
</tbody>
</table>
<% end %>

app/views/categories/edit.html.erb
<h2>Edit category</h2>
<%= form_for @category do |f| %>
<% if @category.errors.any? %>
<h3>Errors:</h3>
<ul>
<% @category.errors.full_messages.each do|msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>
<%= f.label :name %> <!-- <label>Name : </label> -->
<%= f.text_field :name %> <br/>
<%= f.submit "submit" %> or <%= link_to "back", category_path(@category.id) %> or <%= link_to "List", categories_path %>
<% end %>

app/views/categories/index.html.erb
<h2>Listing Categories : <%= @categories.length %></h2>

<% if @categories.empty? %>
	<p>Categories have not been added yet</p>
<% else %>

<ol>
	<% @categories.each do |category| %>
	<li><%= link_to category.name,category_path(category.id) %>
		(<%= Product.where('category_id =?',category.id).length %>)
		<%#= link_to "show", category_path(category.id) %>
	</li>
	<% end %>
</ol>
<% end %>


<%= link_to "Add Category (ror best)", new_category_path, target: "_blank" %> |
<!-- new_category_path return string "/categories/new" -->

<%= link_to "Add Category (ror)", "/categories/new" %> |
<a href="/categories/new">Add Category</a>

<%# link_to "Add Product", new_product_path %>

app/views/categories/new.html.erb
<h2>Add Category</h2>
<!--<form action="/categories" method="post"> -->
<%= form_for @category do |f| %>
<% if @category.errors.any? %>
<h3>Errors:</h3>
<ul>
<% @category.errors.full_messages.each do|msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>
<%= f.label :name %> <!-- <label>Name : </label> -->
<%= f.text_field :name %> 
<%= f.submit "submit" %>
<% end %>

<!-- <form action=".." method="post">
<label>Name</label>
<input type="text">
<input type="submit">
</form> -->


app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<%= link_to "edit", edit_category_path(@category.id) %> |
<%= link_to "destroy", category_path(@category.id), method: :delete, data: {confirm: "Are you sure"} %>
<% @category.sub_categories.each do |sub_category| %>
<h3><%= link_to sub_category.name.upcase, sub_category_path(sub_category.id) %> (<%= sub_category.products.size %>)</h3>
<ul>
<% sub_category.products.each do|product| %>
<li><%= link_to product.name, product_path(product.id) %></li>
<% end %>
</ul>
<% end %>


<% if @products.empty? %>
<p>no products found</p>
<% else %>
<ol>
<% @products.each do|product| %>
<li>
<%= product.name %> <%= product.price %> (<%= product.stock %>)
</li>
<% end %>
</ol>
<% end %>

<p>listing products less than 500</p>
<ol>
<% @products_lessthan500.each do|product| %>
	<li>
	<%= product.name %> <%= product.price %> 
	</li>
<% end %>
</ol>

<p>listing products greater than 500</p>
<ol>
<% @products_greaterthan500.each do|product| %>
<li>
<%= product.name %> <%= product.price %>
</li>
<% end %>
</ol>
<%= link_to "Back", categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
welcome <%= current_user.email %>
<%= link_to "account setting", edit_user_registration_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Login", new_user_session_path %> | <%= link_to "Register", new_user_registration_path %>
<% end %>
<br/>
<%= link_to "Your Cart", cart_line_items_path %> |
<%= link_to "categories", categories_path %> | <%= link_to "products", products_path %> 
<br/>
<%= notice %>
<%= alert %>
<%= yield %>


</body>
</html>

app/views/products/edit.html.erb
<h2>Edit category</h2>

<%=form_for @product do |f| %>
<% if @product.errors.any? %>
<h3>Errors : </h3>
<ul>
<% @product.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= f.label :category_id %><br/>
<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br/>

<%= f.label :sub_category_id %><br/>
<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "select category" %><br/>

<%= f.label :name %><br/>
<%= f.text_field :name %><br/>

<%= f.label :description %><br/>
<%= f.text_area :description, rows: 5, cols: 20 %><br/>

<%= f.label :price %><br/>
<%= f.number_field :price %><br/>

<%= f.label :stock %><br/>
<%= f.number_field :stock %><br/>

<%= f.label :cod_eligibility %><br/>
<%= f.check_box :cod_eligibility %><br/>

<%= f.submit  %>
<% end %>

app/views/products/index.html.erb
<h2>Listing products : <%= @products.length %> </h2>
<% if user_signed_in? && current_user.is_admin %>

<%= link_to "Add Product", new_product_path %>
<% end %>

<% if @products.empty? %>
<p> products have not been added </p>
<% else %>
<ul>
<% @products.each do |product| %>
<li><%= link_to  product.name, product_path(product.id) %> INR
<%= product.price %> --
	<%= product.category.name %>
</li>
<% end %>
</ul>
<% end %>
 




app/views/products/new.html.erb
<h2>Add Product</h2>
<%=form_for @product do |f| %>
<% if @product.errors.any? %>
<h3>Errors : </h3>
<ul>
<% @product.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= f.label :category_id %><br/>
<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br/>

<%= f.label :sub_category_id %><br/>
<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "select category" %><br/>

<%= f.label :name %><br/>
<%= f.text_field :name %><br/>

<%= f.label :description %><br/>
<%= f.text_area :description, rows: 5, cols: 20 %><br/>

<%= f.label :price %><br/>
<%= f.number_field :price %><br/>

<%= f.label :stock %><br/>
<%= f.number_field :stock %><br/>

<%= f.label :cod_eligibility %><br/>
<%= f.check_box :cod_eligibility %><br/>

<%= f.submit  %>
<% end %>

app/views/products/show.html.erb
<h2> Specific product </h2>
<% if user_signed_in? && current_user.is_admin %>
<%= link_to "Edit", edit_product_path(@product.id) %>
<%= link_to "Destroy", product_path(@product.id), method: :delete , data: {confirm:"Are you sure"} %>
<% end %>
<p> Name: <%= @product.name %></p>
<p>Description: <%= @product.description %></p>
<p>Price: <%= @product.price %></p>
<p>Stock:<%= @product.stock %></p>
<p>Cod_eligibility:<%= @product.cod_eligibility %></p>
<p>Category_Name:<%= link_to @product.category.name,category_path(@product.category_id) %></p>
<p>sub category : <%= link_to @product.sub_category.name %> </p>


<%= form_for @cart_line_item do|f| %>
<%= f.label :quantity %>
<%= f.select :quantity, [1,2,3,4,5] %><br/>
<%= f.hidden_field :product_id, value: @product.id %>
<%=f.submit "Add To Cart" %>
<% end %>


    <h2>Reviews:(<%= @product.reviews.length %>)</h2>
    <ol>
    <% @product.reviews.each do |review| %>
     <li>  
           <%= review.user.email %> rated <%= "*" * review.rating %> <br/>
           <%= review.title %> - <%= review.body %> on <%= review.created_at %> <br/>

            <% if user_signed_in? %>
                   <% if review.user_id == current_user.id %>
                           <%= link_to "Destroy", review_path(review.id) %>
                  <% end %>   

      </li>
              <% end %>   
      <% end %>
  </ol>



<% if user_signed_in? %>
<h2> Add Review</h2>
<%= form_for @review do |f| %>
    <%= f.label :rating %><br/>
    <%= f.radio_button :rating,1 %> 1
    <%= f.radio_button :rating,2 %> 2
    <%= f.radio_button :rating,3 %> 3
    <%= f.radio_button :rating,4 %> 4
    <%= f.radio_button :rating,5 %> 5
    <br/>
    <%= f.label :title %><br/>
    <%= f.text_field :title %><br/>

    <%= f.label :Body %><br/>
    <%= f.text_field :body %><br/>

    <%= f.hidden_field :product_id,value: @product.id %>
    <%#= f.hidden_field :user_id,value: current_user.id %>
<%= f.submit %>

<% end %><br/>
<% end %>

<%= link_to "Back",products_path %>

app/views/sub_categories/edit.html.erb
<h2> Editing Existing Subcategory </h2>

<%= form_for @subcategory do |f| %>
<% if @subcategory.errors.any? %>
<ol>
   <% @subcategory.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
   <% end %>
   </ol>
<% end %>
     <%= f.label :Name %>:
     <%= f.text_field :name %><br/>
     <%= f.label :Category %>
     <%= f.collection_select :category_id,Category.all,:id,:name,prompt:"Select category" %><br/>
     <%= f.submit %>
<% end %>
<%= link_to "Back",sub_category_path(@subcategory.id) %>

app/views/sub_categories/index.html.erb
<h2> Listing Sub_Category </h2>

    <% if  @subcategories.empty? %>
    <p>"No Record Found"</p>
    <% else %>
    <ol>
        <% @subcategories.each do |subcategory| %>
         <li> <%= link_to subcategory.name,sub_category_path(subcategory.id) %>-<%= subcategory.category.name %></li>

        <% end %>
    </ol>
    <% end %>
<%= link_to "New SubCategory",new_sub_category_path %>


app/views/sub_categories/new.html.erb
<%= form_for @subcategory do |f| %>
 <% if @subcategory.errors.any? %>
  <ol>
   <% @subcategory.errors.full_messages.each do |msg| %>
       <li> <%= msg %></li>
    <% end %>
  </ol>
<% end %>
<%= f.label :Name %>:
     <%= f.text_field :name %><br/>
     <%= f.label :Category %><br/>
     <%= f.collection_select :category_id,Category.all,:id,:name,prompt:"Select category" %><br/>
     <%= f.submit %>

<% end %>

app/views/sub_categories/show.html.erb
<h2> Specific subcategory record </h2>
<%= link_to "Edit",edit_sub_category_path(@subcategory.id) %> |

<%= link_to "Destroy", sub_category_path(@subcategory.id), method: :delete , data: {confirm:"Are you sure"} %>
<p>Name:<%= @subcategory.name %></p>
<p>Category: <%= @subcategory.category.name %></p>

<%= link_to "Back",sub_categories_path %>